language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

script: ./vendor/bin/phpunit --configuration phpunit.xml.dist --testsuite default